name:
  in: query
  name: name
  required: false
  schema:
    type: string
format:
  in: query
  name: format
  required: false
  schema:
    type: string
size:
  in: query
  name: size
  required: false
  schema:
    type: integer
offset:
  in: query
  name: offset
  required: false
  schema:
    type: integer

