name: |
  Issue Opened

on:
  issues:
    types:
      - opened

permissions: {} # disables permissions for all of the available permissions

jobs:
  add-inbox-milestone:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh issue edit "${{ github.event.issue.number }}" \
          --repo ${{ github.repository }} \
          --milestone "0.inbox"
