name: 'post release'

# Ensures that only one workflow is run per branch at a time.
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}

on:
  # Uncomment the following pull_request event to test this workflow in a PR
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

  workflow_dispatch:

permissions:
  contents: read # for checking out the repository (e.g. actions/checkout)
  pull-requests: write # for reading, and creating pull requests (via peter-evans/create-pull-request)

jobs:
  bump:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/bootstrap/
        with:
          install-cmd: |
            make install
      - name: ''
        run: |
          make bump
      # For testing only hence only on a PR event
      - if: ${{ github.event_name == 'pull_request' }}
        run: |
          git ls-files --exclude-standard --modified --deleted --others -t
          echo 'chore(deps): bump @kumahq/kuma-gui-monorepo'
          echo '=========='
          ls -al ./active-branches.json
